[tasks.default]
alias = "build"

[tasks.build]
dependencies = ["compile", "objcopy"]
clear = true

[tasks.compile]
description = "Compile the kernel into an elf file using 'xargo' (`cargo install xargo`), and a linker script"
command = "xargo"
args = ["rustc", "--target=aarch64-unknown-none-softfloat", "--release", "--", "-C", "link-arg=-Tsrc/linker.ld"]

[tasks.objcopy]
description = "Copy from the elf output into a binary format"
command = "rust-objcopy"
args = ["-Obinary", "target/aarch64-unknown-none-softfloat/release/ferrous", "kernel8.img"]

# These need to be invoked directly

[tasks.run]
dependencies = ["build"]
clear = true
description = "Launch qemu emulation of the kernel"
command = "qemu-system-aarch64"
args = ["-M", "raspi3", "-kernel", "kernel8.img", "-serial", "stdio", "-display", "none"]

[tasks.objdump]
command = "rust-objdump"
description = "Uses rust-objdump to disassemble all headers in the elf output"
args = ["target/aarch64-unknown-none-softfloat/release/ferrous", "-xz"]

[tasks.hexdump]
command = "hx"
description = "Uses 'hx' (`cargo install hx`) to dump the contents of the image"
args = ["kernel8.img"]

